export const initialCommodityData = {
  wti_crude: Array.from({ length: 50 }, (_, i) => ({
    time: i,
    price: 80 + Math.sin(i / 5) * 5 + Math.random() * 2,
  })),
  brent_crude: Array.from({ length: 50 }, (_, i) => ({
    time: i,
    price: 85 + Math.sin(i / 5) * 5 + Math.random() * 2,
  })),
  natural_gas: Array.from({ length: 50 }, (_, i) => ({
    time: i,
    price: 2.5 + Math.cos(i / 4) * 0.5 + Math.random() * 0.2,
  })),
  coal: Array.from({ length: 50 }, (_, i) => ({
    time: i,
    price: 130 + Math.sin(i / 10) * 10 + Math.random() * 5,
  })),
  electricity: Array.from({ length: 50 }, (_, i) => ({
    time: i,
    price: 90 + Math.cos(i / 8) * 15 + Math.random() * 4,
  })),
};

export interface CountryProfile {
  id: number; // numeric ISO 3166-1 for world-atlas matching
  name: string;
  dependency: number; // negative = net exporter, positive = % import dependency
  primary: string; // primary energy source
  renewableShare: number;
  conflictRisk: number; // 0-100
  energyScore: number; // composite cost index 0-100 (higher = more expensive)
  prices: {
    oil: number; // $/bbl
    gas: number; // $/MMBtu
    coal: number; // $/tonne
    electricity: number; // $/kWh
  };
}

export const MOCK_COUNTRY_PROFILES: CountryProfile[] = [
  // ── North America ──────────────────────────────────────────────────────────
  {
    id: 840,
    name: "United States",
    dependency: 15,
    primary: "Oil",
    renewableShare: 20,
    conflictRisk: 10,
    energyScore: 42,
    prices: { oil: 85.2, gas: 3.45, coal: 135.0, electricity: 0.14 },
  },
  {
    id: 124,
    name: "Canada",
    dependency: -20,
    primary: "Oil",
    renewableShare: 67,
    conflictRisk: 5,
    energyScore: 30,
    prices: { oil: 78.5, gas: 2.8, coal: 90.0, electricity: 0.1 },
  },
  {
    id: 484,
    name: "Mexico",
    dependency: 10,
    primary: "Oil",
    renewableShare: 25,
    conflictRisk: 20,
    energyScore: 38,
    prices: { oil: 82.0, gas: 3.1, coal: 110.0, electricity: 0.09 },
  },

  // ── South America ──────────────────────────────────────────────────────────
  {
    id: 76,
    name: "Brazil",
    dependency: 20,
    primary: "Hydro",
    renewableShare: 80,
    conflictRisk: 10,
    energyScore: 35,
    prices: { oil: 82.0, gas: 3.2, coal: 110.0, electricity: 0.12 },
  },
  {
    id: 32,
    name: "Argentina",
    dependency: 25,
    primary: "Gas",
    renewableShare: 32,
    conflictRisk: 15,
    energyScore: 40,
    prices: { oil: 84.0, gas: 3.8, coal: 115.0, electricity: 0.06 },
  },
  {
    id: 152,
    name: "Chile",
    dependency: 70,
    primary: "Oil",
    renewableShare: 45,
    conflictRisk: 10,
    energyScore: 55,
    prices: { oil: 90.0, gas: 6.5, coal: 130.0, electricity: 0.19 },
  },
  {
    id: 170,
    name: "Colombia",
    dependency: -30,
    primary: "Oil",
    renewableShare: 70,
    conflictRisk: 25,
    energyScore: 30,
    prices: { oil: 80.0, gas: 2.5, coal: 95.0, electricity: 0.06 },
  },
  {
    id: 862,
    name: "Venezuela",
    dependency: -80,
    primary: "Oil",
    renewableShare: 68,
    conflictRisk: 70,
    energyScore: 15,
    prices: { oil: 70.0, gas: 0.5, coal: 80.0, electricity: 0.01 },
  },
  {
    id: 604,
    name: "Peru",
    dependency: 30,
    primary: "Hydro",
    renewableShare: 58,
    conflictRisk: 18,
    energyScore: 40,
    prices: { oil: 83.0, gas: 4.0, coal: 112.0, electricity: 0.08 },
  },

  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    id: 276,
    name: "Germany",
    dependency: 65,
    primary: "Gas",
    renewableShare: 45,
    conflictRisk: 40,
    energyScore: 85,
    prices: { oil: 92.5, gas: 8.2, coal: 145.0, electricity: 0.38 },
  },
  {
    id: 826,
    name: "United Kingdom",
    dependency: 50,
    primary: "Gas",
    renewableShare: 43,
    conflictRisk: 20,
    energyScore: 80,
    prices: { oil: 91.0, gas: 9.8, coal: 148.0, electricity: 0.34 },
  },
  {
    id: 250,
    name: "France",
    dependency: 40,
    primary: "Nuclear",
    renewableShare: 25,
    conflictRisk: 15,
    energyScore: 62,
    prices: { oil: 91.0, gas: 7.6, coal: 142.0, electricity: 0.21 },
  },
  {
    id: 380,
    name: "Italy",
    dependency: 75,
    primary: "Gas",
    renewableShare: 40,
    conflictRisk: 20,
    energyScore: 75,
    prices: { oil: 91.5, gas: 9.2, coal: 143.0, electricity: 0.29 },
  },
  {
    id: 724,
    name: "Spain",
    dependency: 70,
    primary: "Oil",
    renewableShare: 47,
    conflictRisk: 10,
    energyScore: 68,
    prices: { oil: 91.0, gas: 8.0, coal: 140.0, electricity: 0.24 },
  },
  {
    id: 528,
    name: "Netherlands",
    dependency: 60,
    primary: "Gas",
    renewableShare: 33,
    conflictRisk: 15,
    energyScore: 78,
    prices: { oil: 92.0, gas: 9.5, coal: 144.0, electricity: 0.32 },
  },
  {
    id: 616,
    name: "Poland",
    dependency: 45,
    primary: "Coal",
    renewableShare: 18,
    conflictRisk: 50,
    energyScore: 65,
    prices: { oil: 90.0, gas: 7.8, coal: 138.0, electricity: 0.2 },
  },
  {
    id: 752,
    name: "Sweden",
    dependency: 30,
    primary: "Nuclear",
    renewableShare: 65,
    conflictRisk: 10,
    energyScore: 55,
    prices: { oil: 89.0, gas: 6.5, coal: 130.0, electricity: 0.18 },
  },
  {
    id: 578,
    name: "Norway",
    dependency: -200,
    primary: "Hydro",
    renewableShare: 98,
    conflictRisk: 5,
    energyScore: 20,
    prices: { oil: 75.0, gas: 1.5, coal: 80.0, electricity: 0.07 },
  },
  {
    id: 804,
    name: "Ukraine",
    dependency: 50,
    primary: "Nuclear",
    renewableShare: 15,
    conflictRisk: 95,
    energyScore: 88,
    prices: { oil: 95.0, gas: 12.4, coal: 160.0, electricity: 0.08 },
  },
  {
    id: 643,
    name: "Russia",
    dependency: -200,
    primary: "Gas",
    renewableShare: 18,
    conflictRisk: 85,
    energyScore: 12,
    prices: { oil: 70.0, gas: 1.8, coal: 90.0, electricity: 0.05 },
  },
  {
    id: 792,
    name: "Turkey",
    dependency: 75,
    primary: "Oil",
    renewableShare: 42,
    conflictRisk: 45,
    energyScore: 65,
    prices: { oil: 91.0, gas: 8.4, coal: 140.0, electricity: 0.1 },
  },
  {
    id: 246,
    name: "Finland",
    dependency: 55,
    primary: "Nuclear",
    renewableShare: 42,
    conflictRisk: 20,
    energyScore: 70,
    prices: { oil: 90.0, gas: 8.2, coal: 140.0, electricity: 0.19 },
  },
  {
    id: 208,
    name: "Denmark",
    dependency: -10,
    primary: "Wind",
    renewableShare: 80,
    conflictRisk: 5,
    energyScore: 90,
    prices: { oil: 91.0, gas: 9.8, coal: 145.0, electricity: 0.37 },
  },
  {
    id: 620,
    name: "Portugal",
    dependency: 80,
    primary: "Wind",
    renewableShare: 61,
    conflictRisk: 5,
    energyScore: 58,
    prices: { oil: 91.0, gas: 7.5, coal: 138.0, electricity: 0.22 },
  },
  {
    id: 642,
    name: "Romania",
    dependency: 20,
    primary: "Gas",
    renewableShare: 42,
    conflictRisk: 30,
    energyScore: 48,
    prices: { oil: 89.0, gas: 6.2, coal: 128.0, electricity: 0.15 },
  },

  // ── Russia / Central Asia ──────────────────────────────────────────────────
  {
    id: 398,
    name: "Kazakhstan",
    dependency: -80,
    primary: "Oil",
    renewableShare: 5,
    conflictRisk: 30,
    energyScore: 25,
    prices: { oil: 74.0, gas: 2.0, coal: 88.0, electricity: 0.06 },
  },
  {
    id: 860,
    name: "Uzbekistan",
    dependency: -30,
    primary: "Gas",
    renewableShare: 8,
    conflictRisk: 25,
    energyScore: 28,
    prices: { oil: 76.0, gas: 1.8, coal: 90.0, electricity: 0.04 },
  },

  // ── Middle East ────────────────────────────────────────────────────────────
  {
    id: 682,
    name: "Saudi Arabia",
    dependency: -300,
    primary: "Oil",
    renewableShare: 2,
    conflictRisk: 50,
    energyScore: 8,
    prices: { oil: 60.0, gas: 0.75, coal: 70.0, electricity: 0.05 },
  },
  {
    id: 784,
    name: "UAE",
    dependency: -200,
    primary: "Oil",
    renewableShare: 5,
    conflictRisk: 30,
    energyScore: 10,
    prices: { oil: 65.0, gas: 1.0, coal: 75.0, electricity: 0.08 },
  },
  {
    id: 634,
    name: "Qatar",
    dependency: -500,
    primary: "Gas",
    renewableShare: 0,
    conflictRisk: 25,
    energyScore: 5,
    prices: { oil: 62.0, gas: 0.5, coal: 65.0, electricity: 0.04 },
  },
  {
    id: 368,
    name: "Iraq",
    dependency: -200,
    primary: "Oil",
    renewableShare: 4,
    conflictRisk: 80,
    energyScore: 18,
    prices: { oil: 68.0, gas: 1.2, coal: 80.0, electricity: 0.04 },
  },
  {
    id: 364,
    name: "Iran",
    dependency: -200,
    primary: "Oil",
    renewableShare: 7,
    conflictRisk: 75,
    energyScore: 15,
    prices: { oil: 68.0, gas: 1.0, coal: 78.0, electricity: 0.03 },
  },
  {
    id: 414,
    name: "Kuwait",
    dependency: -400,
    primary: "Oil",
    renewableShare: 1,
    conflictRisk: 40,
    energyScore: 6,
    prices: { oil: 58.0, gas: 0.6, coal: 60.0, electricity: 0.03 },
  },

  // ── Asia-Pacific ───────────────────────────────────────────────────────────
  {
    id: 156,
    name: "China",
    dependency: 80,
    primary: "Coal",
    renewableShare: 30,
    conflictRisk: 20,
    energyScore: 52,
    prices: { oil: 88.0, gas: 5.1, coal: 120.0, electricity: 0.08 },
  },
  {
    id: 356,
    name: "India",
    dependency: 85,
    primary: "Coal",
    renewableShare: 22,
    conflictRisk: 30,
    energyScore: 48,
    prices: { oil: 87.5, gas: 4.8, coal: 118.0, electricity: 0.09 },
  },
  {
    id: 392,
    name: "Japan",
    dependency: 90,
    primary: "LNG",
    renewableShare: 22,
    conflictRisk: 15,
    energyScore: 72,
    prices: { oil: 93.0, gas: 12.5, coal: 150.0, electricity: 0.28 },
  },
  {
    id: 410,
    name: "South Korea",
    dependency: 93,
    primary: "LNG",
    renewableShare: 8,
    conflictRisk: 30,
    energyScore: 68,
    prices: { oil: 92.0, gas: 11.0, coal: 148.0, electricity: 0.11 },
  },
  {
    id: 360,
    name: "Indonesia",
    dependency: -20,
    primary: "Coal",
    renewableShare: 14,
    conflictRisk: 20,
    energyScore: 30,
    prices: { oil: 82.0, gas: 3.0, coal: 100.0, electricity: 0.09 },
  },
  {
    id: 458,
    name: "Malaysia",
    dependency: -40,
    primary: "Gas",
    renewableShare: 22,
    conflictRisk: 10,
    energyScore: 28,
    prices: { oil: 80.0, gas: 2.4, coal: 95.0, electricity: 0.06 },
  },
  {
    id: 764,
    name: "Thailand",
    dependency: 60,
    primary: "Gas",
    renewableShare: 18,
    conflictRisk: 15,
    energyScore: 50,
    prices: { oil: 88.0, gas: 5.8, coal: 125.0, electricity: 0.13 },
  },
  {
    id: 704,
    name: "Vietnam",
    dependency: 30,
    primary: "Coal",
    renewableShare: 32,
    conflictRisk: 10,
    energyScore: 38,
    prices: { oil: 85.0, gas: 4.2, coal: 110.0, electricity: 0.08 },
  },
  {
    id: 586,
    name: "Pakistan",
    dependency: 80,
    primary: "Gas",
    renewableShare: 32,
    conflictRisk: 50,
    energyScore: 55,
    prices: { oil: 88.0, gas: 5.5, coal: 125.0, electricity: 0.1 },
  },
  {
    id: 608,
    name: "Philippines",
    dependency: 65,
    primary: "Oil",
    renewableShare: 28,
    conflictRisk: 20,
    energyScore: 58,
    prices: { oil: 90.0, gas: 6.8, coal: 132.0, electricity: 0.18 },
  },
  {
    id: 36,
    name: "Australia",
    dependency: -30,
    primary: "Coal",
    renewableShare: 32,
    conflictRisk: 5,
    energyScore: 55,
    prices: { oil: 88.0, gas: 6.0, coal: 125.0, electricity: 0.24 },
  },
  {
    id: 554,
    name: "New Zealand",
    dependency: 30,
    primary: "Hydro",
    renewableShare: 82,
    conflictRisk: 5,
    energyScore: 50,
    prices: { oil: 88.0, gas: 5.5, coal: 120.0, electricity: 0.2 },
  },
  {
    id: 104,
    name: "Myanmar",
    dependency: -10,
    primary: "Gas",
    renewableShare: 46,
    conflictRisk: 70,
    energyScore: 32,
    prices: { oil: 81.0, gas: 3.0, coal: 98.0, electricity: 0.06 },
  },
  {
    id: 50,
    name: "Bangladesh",
    dependency: 60,
    primary: "Gas",
    renewableShare: 10,
    conflictRisk: 25,
    energyScore: 45,
    prices: { oil: 87.0, gas: 4.6, coal: 118.0, electricity: 0.08 },
  },

  // ── Africa ─────────────────────────────────────────────────────────────────
  {
    id: 710,
    name: "South Africa",
    dependency: 30,
    primary: "Coal",
    renewableShare: 12,
    conflictRisk: 20,
    energyScore: 45,
    prices: { oil: 86.0, gas: 4.5, coal: 115.0, electricity: 0.11 },
  },
  {
    id: 566,
    name: "Nigeria",
    dependency: -100,
    primary: "Oil",
    renewableShare: 20,
    conflictRisk: 60,
    energyScore: 22,
    prices: { oil: 75.0, gas: 1.5, coal: 85.0, electricity: 0.06 },
  },
  {
    id: 818,
    name: "Egypt",
    dependency: 20,
    primary: "Gas",
    renewableShare: 11,
    conflictRisk: 40,
    energyScore: 38,
    prices: { oil: 83.0, gas: 3.2, coal: 105.0, electricity: 0.04 },
  },
  {
    id: 12,
    name: "Algeria",
    dependency: -100,
    primary: "Gas",
    renewableShare: 2,
    conflictRisk: 35,
    energyScore: 20,
    prices: { oil: 72.0, gas: 1.8, coal: 85.0, electricity: 0.04 },
  },
  {
    id: 231,
    name: "Ethiopia",
    dependency: 20,
    primary: "Hydro",
    renewableShare: 92,
    conflictRisk: 55,
    energyScore: 30,
    prices: { oil: 83.0, gas: 3.5, coal: 100.0, electricity: 0.04 },
  },
  {
    id: 288,
    name: "Ghana",
    dependency: -10,
    primary: "Oil",
    renewableShare: 42,
    conflictRisk: 20,
    energyScore: 32,
    prices: { oil: 80.0, gas: 2.8, coal: 95.0, electricity: 0.07 },
  },
  {
    id: 716,
    name: "Zimbabwe",
    dependency: 40,
    primary: "Coal",
    renewableShare: 22,
    conflictRisk: 40,
    energyScore: 42,
    prices: { oil: 86.0, gas: 4.2, coal: 112.0, electricity: 0.06 },
  },
];
